const boilers = [
    {
        path: 'paku-500-kvt-1k-nr',
        imgSrc: "/src/assets/images/boilers/paku-500-kvt-1k-nr/1-small.png",
        images: [
            '/src/assets/images/boilers/paku-500-kvt-1k-nr/1.png',
            '/src/assets/images/boilers/paku-500-kvt-1k-nr/2.png',
        ],
        type: "ПАКУ 500 кВт 1К (Н/Р)",
        purpose: "Теплоснабжение",
        typeDescription: "Блочно-модульная автоматизированная котельная",
        manufactureDate: "Февраль - 2023г",
        boiler: "Wiesberg Steel 501",
        boilerCount: 1,
        available: 2,
        fullDescription: "Котельная предназначена для обеспечения потребителей тепловой энергией в виде теплоснабжения (отопление), а так же для растопки ледовых покрытий. Котельная автоматизирована и работает без постоянного присутствия обслуживающего персонала. После доставки котла на место установки подключение к коммуникациям занимает не более двух часов, пуск котла и выход его на номинальные параметры также занимают около двух часов. В состав оборудования котельной входит котёл, горелочное устройство, насос циркуляционный фланцевый. ПАКУ имеет небольшие габариты и малый вес, что позволяет устанавливать котел в кузов грузового транспортного средства (газель) и работать непосредственно с него.",
        serviceLife: "Не менее 10 лет",
        electricPower: "6 кВт",
        electricalPowerConsumption: "8 кВт",
        weight: "Не более 1,5 т.",
        fuelType: "ГАЗ/Дизель",
        power: "500 кВт",
        fuelConsumption: "20-60 л/час",
        coolantTemperature: "95°С",
        burnersCount: "1",
        burnerType: "Мазутно-дизельная двухступенчатая Baltur TBL 60P 200 - 600 кВт",
        coolantPressure: "0,6-0,5 МПа",
        fuelTank: "наружный (кубик)",
        heatingCapacity: "0,43 Гкал/ч",
        boilerEfficiency: "93%",
        LxWxH: "2580x1300x1900 мм",
    },
    
    {
        path: 'bmak-1000-kvt-2k',
        imgSrc: "/src/assets/images/boiler-1000.png",
        images: [
            "/src/assets/images/boiler-1000.png"
        ],
        type: "ПАКУ 1000 кВт 2К (Н/Р)",
        purpose: "Теплоснабжение",
        typeDescription: "Блочно-модульная автоматизированная котельная",
        manufactureDate: "Январь - 2024г",
        fuelType: "ГАЗ/Дизель",
        bmkBuilding: "На базе морского контейнера 20футов",
        boiler: "Buderus Logano SK755",
        boilerCount: 2,
        available: 5,
        power: "1000 кВт",
        burnerType: "Мазутно-дизельная двухступенчатая Uret UM3 226-564 кВт",
        burnersCount: "2",
        pump: "CNP/Purity с устройством плавного пуска",
        fuelTank: "6,0м3",
        fuelConsumption: "110 л/час",
        heatingSystem: "Независимая (двухконтурная с теплообменником)",
        boilerCircuit: "пропиленгликоль -55°С",
        boilerCircuitTemperature: "100-75°С",
        heatCarrier: "гликоли/вода",
        heatCarrierTemp: "95-70°С",
        electricPower: "22 кВт",
        electricalPowerConsumption: "15 кВт",
        backupPowerSupply: "Встроенной Бензогенератор TSS SGG 18000EH3LA с АВР",
        boilerCircuitCoolantPressure: "0,2-0,6 Мпа",
        networkCircuitCoolantPressure: "0,2-1,2 Мпа",
        temperatureControl: "Качественное",
        boilerEfficiency: "94-96%",
        heatingCapacity: "0,859 Гкал/ч",
        fireSecurityAlarm: "ВЕРС ПК2",
        dispatching: "На базе ПЛК ОВЕН (удалённый мониторинг и управление котельной, архивация данных 90 суток)",
        fullDescription: "Котельная автоматизирована и работает без постоянного присутствия персонала - полностью дистанционный доступ управления котельной. В состав котельной входит резервный генератор, на случай отключения электричества. Блочно-модульная автоматизированная котельная обладает высокой степенью эксплуатационной готовности. Монтаж котельной на фундаменте и подключение к коммуникациям занимает не более 2-х суток.",
        stovepipe: "быстросъёмные, секционные сэндвич из нержавеющей стали",
        weight: "Не более 10 т",
        LxWxH: "6060x2440x2590 мм",
    },
    {
        path: '2',
        imgSrc: "/src/assets/images/boiler-1200.png",
        type: "БМАК 1040 кВт 1К",
        purpose: "Теплоснабжение",
        typeDescription: "Блочно-модульная автоматизированная котельная",
        manufactureDate: "Январь - 2024г",
        boiler: "Buderus Logano SK755",
        boilerCount: 1,
        power: "1040 кВт",
        available: 5,
        fullDescription: ""
    },
    {
        path: '2',
        imgSrc: "/src/assets/images/boiler-1000.png",
        type: "БМАК 1200 кВт 1К",
        purpose: "Теплоснабжение",
        typeDescription: "Блочно-модульная автоматизированная котельная",
        manufactureDate: "Ноябрь - 2022г",
        boiler: "Temron WL-1250",
        boilerCount: 1,
        power: "1200 кВт",
        available: 5,
    },
    {
        path: '2',
        imgSrc: "/src/assets/images/boiler-1200.png",
        type: "БМАК 1400 кВт 1К",
        purpose: "Теплоснабжение",
        typeDescription: "Блочно-модульная автоматизированная котельная",
        manufactureDate: "Декабрь - 2022г.",
        boiler: "Buderus Logano SK755",
        boilerCount: 1,
        power: "1400 кВт",
        available: 5,
    },
    {
        path: '2',
        imgSrc: "/src/assets/images/boiler-1000.png",
        type: "БМАК 1600 кВт 1К",
        purpose: "Теплоснабжение",
        typeDescription: "Автоматизированная газовая горелка",
        manufactureDate: "Ноябрь - 2022г.",
        boiler: "Temron WL-1750",
        boilerCount: 1,
        power: "1600 кВт",
        available: 5,
    },
    {
        path: '2',
        imgSrc: "/src/assets/images/boiler-1200.png",
        type: "БМАК 4800 кВт 2К",
        purpose: "Теплоснабжение",
        typeDescription: "Автоматизированная газовая горелка",
        manufactureDate: "Ноябрь - 2022г.",
        boiler: "Sibiria 2,5 кВт",
        boilerCount: 2,
        power: "4800 кВт",
        available: 5,
    },
    {
        path: '2',
        imgSrc: "/src/assets/images/boiler-1200.png",
        type: "БМАК 6000 кВт 2К",
        purpose: "Теплоснабжение",
        typeDescription: "Автоматизированная газовая горелка",
        manufactureDate: "Ноябрь - 2022г.",
        boiler: "Sibiria 3,0 кВт",
        boilerCount: 2,
        power: "6000 кВт",
        available: 5,
    },
    {
        path: '2',
        imgSrc: "/src/assets/images/boiler-1200.png",
        type: "БМАК 6100 кВт 2К",
        purpose: "Теплоснабжение",
        typeDescription: "Автоматизированная газовая горелка",
        manufactureDate: "Ноябрь - 2022г.",
        boiler: "Bosch UT-L24",
        boilerCount: 2,
        power: "6100 кВт",
        available: 5,
    },
    {
        path: '2',
        imgSrc: "/src/assets/images/boiler-1200.png",
        type: "БМАК 7400 кВт 2К",
        purpose: "Теплоснабжение",
        typeDescription: "Автоматизированная газовая горелка",
        manufactureDate: "Ноябрь - 2022г.",
        boiler: "Bosch UT-L28",
        boilerCount: 2,
        power: "7400 кВт",
        available: 5,
    },
];

export {
    boilers,
};